version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
  recipe-rest:
    image: recipe-rest
    restart: always
    ports:
      - "8081:8080"
  recipe-web:
    image: recipe-web
    restart: always
    ports:
      - "8080:8080"
